<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CausaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CausaRepository extends EntityRepository
{
}
