<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubtipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubtipoRepository extends EntityRepository
{
}
